### ISSUE TITLE
Latest update getting JSON praise error 

### ISSUE THREAD

**Issue by krishne35** [sp-engineering/frigate-viewer#24] opened 2024-10-10 15:53 UTC
![Screenshot_2024-10-10-21-21-48-41_01fc1bff8dd830c6a60eb317a0de2fc0.jpg](https://github.com/user-attachments/assets/203dae6b-592a-4ac7-8b58-06cc114ffbab)

Have configured everything with password and username but getting unexpected character <

**Comment by piwko28** [comment] 2024-10-11 09:31
Similar issue to #23 

The error occurs when wrong path, username or password were provided. Please double check it.
Are you using http or https? Does the other tabs work, ie. Storage?

**Comment by krishne35** [comment] 2024-10-11 09:58
Https via traefik reverse proxy
USERNAME and PASSWORD are correct

What am I supposed to fill in path?

**Comment by piwko28** [comment] 2024-10-11 13:38
Nothing. Maybe it's not clear enough.
[protocol]://[host]:[port]/[path]

So if your frigate GUI is under:
https://frigate.local:5000
you should leave path empty.

But if it's in subdirectory:
https://homeserver.local:5000/my_frigate
the path should be "my_frigate"

**Comment by Xaervyn** [comment] 2024-10-12 04:18
I am experiencing the same issue. 

I am able to access Frigate through the web page using  https://192.168.1.128:8971

However, when configuring the app with the same username and password, and the relevant protocol, IP address, and port, with path as empty, I am getting the same error as OP.

**Comment by krishne35** [comment] 2024-10-12 04:24
> Nothing. Maybe it's not clear enough.
> [protocol]://[host]:[port]/[path]
> 
> So if your frigate GUI is under:
> https://frigate.local:5000
> you should leave path empty.
> 
> But if it's in subdirectory:
> https://homeserver.local:5000/my_frigate
> the path should be "my_frigate"

My path is simple

https://frigate.domain.com

**Comment by piwko28** [comment] 2024-10-13 16:54
New update introduces clear notification when username or password is incorrect.
It should also provide anonymous debug info to better understand the issues (it may be disabled in settings), but probably it will not give helpful info for this particular case.

Would be perfect if anyone could provide a reverse proxy configuration or anything else to reproduce the issue.

**Comment by krishne35** [comment] 2024-10-13 17:09
> New update introduces clear notification when username or password is incorrect.
> It should also provide anonymous debug info to better understand the issues (it may be disabled in settings), but probably it will not give helpful info for this particular case.
> 
> Would be perfect if anyone could provide a reverse proxy configuration or anything else to reproduce the issue.

![Screenshot_2024-10-13-22-31-54-45_01fc1bff8dd830c6a60eb317a0de2fc0.jpg](https://github.com/user-attachments/assets/0aca2bee-1c10-4288-a4b6-9828862968a8)

So I'm running traefik as reverse proxy

![IMG_20241013_223515.jpg](https://github.com/user-attachments/assets/33433226-cd1b-4ca9-adb1-e7426657f637)

to-frigate:
      rule: "Host(`xxxxxxx`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: frigate


frigate:
      loadBalancer:
        passHostHeader: true
        serversTransport: "pve"
        servers:
        - url: https://100.0.0.7:8971
serversTransports:
    pve:
      insecureSkipVerify: true

**Comment by piwko28** [comment] 2024-10-14 19:08
I found an issue: Newly entered login credentials were only used after closing and reopening the app, not immediately after saving the settings. I fixed it in newest release 14.2.1, and it potentially fixes the issue. Please let me know if you still encounter the issue.

**Comment by Xaervyn** [comment] 2024-10-14 19:12
I'll try it out and let you know once it appears in the Play Store

**Comment by krishne35** [comment] 2024-10-15 01:17
No luck still same issue
Uninstalled and reinstalled
Manually typed the password still no luck

**Comment by Xaervyn** [comment] 2024-10-15 03:04
![Screenshot_20241014-230143](https://github.com/user-attachments/assets/2e985485-836b-4982-ad41-a771f8160dfd)
I'm getting a different error now, when using the same username and password I used for the Web version

**Comment by Xaervyn** [comment] 2024-10-15 03:20
Oh, it might be something with my network setup. I'll check my firewall rules tomorrow.

**Comment by krishne35** [comment] 2024-10-15 03:22
Try https and see if it works 
> Oh, it might be something with my network setup. I'll check my firewall rules tomorrow.

**Comment by Xaervyn** [comment] 2024-10-16 01:39
> Try https and see if it works
> 
> > Oh, it might be something with my network setup. I'll check my firewall rules tomorrow.

I disabled TLS in my Frigate configuration, because it doesn't work with Traefik, my Reverse Proxy.

I tested it again after enabling the firewall rule for 192.168.2.1/24 > 192.168.1.128:ANY traffic, and although I can now access the webpage from my phone through an internet browser, I'm still unable to connect the FrigateViewer app to my server. I'm receiving the error message "Wrong Credentials". I know the credentials are correct, because they're stored in Bitwarden. I did attempt to freetype the password just in case it was something weird with it autofilling the field, but I had the same results.

@krishne35 , are you still experiencing issues with the settings in the FrigateViewer app, or is it just me? I saw the update was posted to the Google Play store shortly before I posted my comment yesterday. You may need to go into the Play Store and update manually, if you haven't already.

**Comment by piwko28** [comment] 2024-10-16 16:56
Thanks for your input, especially @krishne35 . I reproduced the issue by installing Traefik. It seems that self-signed certificates were not accepted, while it's quite common for Frigate users. New version has been released with the fix.

I know @Xaervyn that you tried to use http and it also failed, but I have an impression that there are more than one case, which makes the issue harder to investigate.

Please let me know if there is still an issue after updating to 4.2.2.

**Comment by krishne35** [comment] 2024-10-16 17:03
Can you share the apk file coz it take a while to show up on playstore

**Comment by krishne35** [comment] 2024-10-16 17:48
Still no luck still getting wrong creds even with 14.2.2
Trued disabling tls and forward it directly to http on traefik yet wrong credentials

**Comment by Xaervyn** [comment] 2024-10-17 02:44
I'm also still having issues with "Wrong Credentials" when connecting to frigate using both the Traefik reverse proxy https address, as well as using the direct ip address with http protocol. I've used both of these addresses from the browser on my phone without encountering issues.

**Comment by piwko28** [comment] 2024-10-17 06:51
Really weird. I have no more ideas.
I need a broken environment to investigate it, or minimal reproducible example to create one.

**Comment by piwko28** [comment] 2024-10-17 07:03
I have one idea. I must upgraded SDK from 33 to 34 (Android 14+), and one of the changes of new SDK is more restricted networking policy. It's strange that I have no issues with it. My phone has older Android, but I use emulator with new SDK. However, I'll try to fix it blindly and we'll see.

**Comment by Xaervyn** [comment] 2024-10-17 15:18
Thank you. I am using a phone with Android 14, so that does sound like a possibility.

I found that Android 14 also automatically enables something called Private DNS, which will ignore the DNS servers provided to it by the DHCP server, and instead use cloudflare, google, or another provider. This was causing issues with me not being able to navigate to my Frigate server using Traefik. Unfortunately, turning this off did not correct the overall issue of it saying the credentials are wrong.

**Comment by ItsMeMegaMind** [comment] 2024-10-31 01:54
@piwko28 Sorry for hijacking this thread. I can see you have added support for frigate authentication. Will it be possible to release a new apk. I tried compiling myself but i could only generate the debug one not the release one.

**Comment by piwko28** [comment] 2024-10-31 09:27
I'll push new update soon. Unfortunately I'm not able to share an apk file here, because it's much heavier than Play store update.

**Comment by piwko28** [comment] 2024-10-31 20:10
@ItsMeMegaMind the changes will be available for beta testers soon, probably today. It contains changes which affects the whole application, so I need to perform regression tests before publishing. If you wish to try it, sign up to beta testers program (should be available on application page in Play store).

**Comment by ItsMeMegaMind** [comment] 2024-11-02 01:26
@piwko28 I just signed up for the beta and installed the update. Worked like a charm. Thank you.

**Comment by piwko28** [comment] 2024-11-02 06:17
Great, nice to hear! Anyone else can test it? @Xaervyn , @krishne35 ?

**Comment by piwko28** [comment] 2024-11-02 06:33
@ItsMeMegaMind is event payback working at your side (when you click one on events list).

**Comment by krishne35** [comment] 2024-11-02 07:57
Can login fine now but when I select any event it force closes

**Comment by ItsMeMegaMind** [comment] 2024-11-02 14:02
It's the same thing on mine too. It logs in and does live streams fine but opening an event crashes the app.

**Comment by piwko28** [comment] 2024-11-02 16:30
Ok, thanks, same on my side. But it's the only bug that I found. I'm not able to fix it today, I'll release fixed version on Monday.

**Comment by piwko28** [comment] 2024-11-04 06:57
New version has been released and should be available publicly for all users.

**Closed** 2024-11-04 06:58 UTC
Labels: question

**Comment by Xaervyn** [comment] 2024-11-07 17:12
Sorry, I was out of town when you posted this, and was unable to test within my local environment. I returned today, and it is working great. Thank you so much!

**Comment by krishne35** [comment] 2024-11-07 17:14
> New version has been released and should be available publicly for all users.
ALL mentioned errors were fixed with new version
Thank you :)
