### ISSUE TITLE
Since last update nothing is working

### ISSUE THREAD

**Issue by AxelHoss** [sp-engineering/frigate-viewer#23] opened 2024-10-05 08:27 UTC
Hi, since your last update (Oktober 2nd) i cant view any cameras. Just when i open the app i can see my camera for a millisecond. Log doesnt say anything. Im the only one with this issue? Homepage working well

**Comment by piwko28** [comment] 2024-10-08 08:27
Can you send some screenshots? What kind of device?

**Comment by AxelHoss** [comment] 2024-10-08 19:19
![Screenshot_2024-10-08-21-18-32-480_com android settings](https://github.com/user-attachments/assets/5e3cbcac-e43d-4624-84af-d7afa9f03fa7)
![Screenshot_2024-10-08-21-17-31-314_com frigateviewer](https://github.com/user-attachments/assets/67255770-6194-4638-a8bd-512caadbb95d)
![Screenshot_2024-10-08-21-17-22-116_com frigateviewer](https://github.com/user-attachments/assets/53d2d63a-afd3-468c-8e43-15e4d7d9dee4)
![Screenshot_2024-10-08-21-16-54-012_com frigateviewer](https://github.com/user-attachments/assets/7a4c98ba-1452-4da0-8f8f-a0ed4a77fc1d)

**Comment by piwko28** [comment] 2024-10-09 20:14
Thanks for sharing.
Currently I have no possibility to check it on Hyper OS.
Could you please clear app data (or uninstall and install again) and try to fill the settings again?
If it does not help - could you try to use demo server, just for test?

**Comment by AxelHoss** [comment] 2024-10-10 02:46
Demo Server is working. Ive deleted the app an reinstalled. Nothing changed. Im the only one with this issue?

**Comment by AxelHoss** [comment] 2024-10-10 13:45
Http

**Comment by piwko28** [comment] 2024-10-11 09:28
I made a test platform and it's working as intended. The error occurs when I provide wrong server data, in example password, but then nothing works including Storge info. Have you tried with other phone model? Any chance to share your Frigate instance for one day to check the reason? If so, please contact me via email.

**Comment by piwko28** [comment] 2024-10-11 13:39
Just to be sure: did you left "path" completely empty?

**Comment by AxelHoss** [comment] 2024-10-11 14:55
path is empty. Btw, the german translation here is wrong. Should be "Pfad" and not "Pfed". 
Tried another hyperOs (have just hyperOs) and got the same issue. Whould you try it via wireguard?

**Comment by piwko28** [comment] 2024-10-13 16:48
No, I haven't. Wireguard shouldn't have impact on it.

**Comment by gulo101** [comment] 2024-10-13 23:22
I am experiencing the same issue. When I pull down to refresh, the cameras flash for a millisecond and then it's just a blank screen. There are no events either.

**Comment by piwko28** [comment] 2024-10-14 19:07
I found an issue: Newly entered login credentials were only used after closing and reopening the app, not immediately after saving the settings. I fixed it in newest release 14.2.1, and it potentially fixes the issue. Please let me know if you still encounter the issue.

**Comment by gulo101** [comment] 2024-10-14 22:05
I updated to 14.2.1 but still seeing the same issue.

**Comment by AxelHoss** [comment] 2024-10-15 00:49
Same here

**Comment by piwko28** [comment] 2024-10-16 17:02
I fixed an issue related to authorization for those who use self-signed certificates.

@AxelHoss you mentioned that your instance uses http though. Are you able to write an instruction how you configured authorization? I want to reproduce your case.

**Comment by pixielark** [comment] 2024-10-19 17:55
Hi piwko28
I think the auth problem is because the auth token is not attached to the request properly

error log from frigate side
```
2024-10-19 10:21:10.560320071  172.19.0.121 - admin [19/Oct/2024:10:21:10 -0700] "GET /api/config HTTP/1.1" 401 179 "-" "okhttp/4.9.2" "2604:4080:redacted"

2024-10-19 10:21:10.603856482  172.19.0.121 - admin [19/Oct/2024:10:21:10 -0700] "GET /api/config HTTP/1.1" 401 179 "-" "okhttp/4.9.2" "2604:4080:redacted"
```

I do not see any log on frigate side that indicate the viewer is trying to retrieve auth token, so I checked the auth code [here](https://github.com/sp-engineering/frigate-viewer/blob/9c706b0395c811bfe15990b9992ffac2d8456aa8/helpers/rest.ts#L6-L15), and looks like there is no action to call the login API to retrieve the auth token and use it for all subsequent API access

entire auth workflow can be found [here](https://github.com/OldTyT/frigate-telegram/issues/15#issuecomment-2333741000)

My guess why you did not encounter the problem is because you are accessing port 5000 for API access but not 8971 which is guarded by auth?

You will need to attach `frigate_token` in the cookie section of the request for API access to work. `frigate_token` is the default value according to the [reference doc](https://docs.frigate.video/configuration/reference/) and it is configurable, which means you might need to add a section on UI to match it as well

and I would guess the cookie will need to be attached somewhere around [here](https://github.com/sp-engineering/frigate-viewer/blob/9c706b0395c811bfe15990b9992ffac2d8456aa8/android/app/src/main/java/com/frigateviewer/IgnoreSSLFactory.java#L46-L55)

hope this can help :smile:

**Comment by piwko28** [comment] 2024-10-20 10:13
@pixielark that helps a lot! I had no idea that Frigate introduced own authentication mechanism! I based on reverse proxy chapter, where they described basic auth - and the Frigate Viewer uses basic auth. Thanks for the remark, I'll analyze the Frigate authentication docs.

**Comment by piwko28** [comment] 2024-11-04 07:03
Authorization is done and new version released. 
Going back to original issue with no cameras: 
@gulo101 which phone model and Android version do you use?

**Comment by gulo101** [comment] 2024-11-04 15:52
> Authorization is done and new version released. Going back to original issue with no cameras: @gulo101 which phone model and Android version do you use?

I am using Pixel 6 Pro. I was actually running Android 13 and last week I had to get a new phone (also Pixel 6 Pro) which came with Android 14. Same issue on both - the app opens, I see the thumbnails for last event for all the cameras for half a second, and then it just goes blank.

**Comment by MYeager1967** [comment] 2024-11-04 20:11
I'm trying to connect through NGINX. What settings do I need to add where in order to get this to work? I have NGINX pointing to port 8971....

**Comment by gulo101** [comment] 2024-12-01 05:49
> Authorization is done and new version released. Going back to original issue with no cameras: @gulo101 which phone model and Android version do you use?

I think the issue was that my Frigate installation was old. I was still on 0.10. I just upgraded to 0.14 and I can see the cameras and recordings again. However now it does crash when I click on the "Settings" button.

**Comment by AxelHoss** [comment] 2024-12-01 08:09
ok ur right. Update to the last frigate version solved the problem. Sorry for the trouble

**Comment by piwko28** [comment] 2024-12-02 14:55
That's wonderfull news, @AxelHoss and @gulo101 ! Thanks for giving me know. I'll have a HyperOS for tests soon, but it seems that it wasn't an issue.

Version of the app is the supported Frigate NVR server version. Maybe I should consider to inform the user when it does not fit to avoid confusion.

@gulo101 try to clear app data or reinstall the app. Let me know if the problem still occurs.

**Closed by piwko28** 2024-12-02 14:55 UTC
Labels: question

**Comment by gulo101** [comment] 2024-12-02 18:46
> @gulo101 try to clear app data or reinstall the app. Let me know if the problem still occurs.

Reinstalling the app fixed it, everything is working now. Thanks!
